#!/usr/bin/env -S bash -e

# Cleaning the TTY.
clear

# Cosmetics (colours for text).
BOLD='\e[1m'
BRED='\e[91m'
BBLUE='\e[34m'  
BGREEN='\e[92m'
BYELLOW='\e[93m'
RESET='\e[0m'

# Pretty print (function).
info_print () {
    echo -e "${BOLD}${BGREEN}[ ${BBLUE}•${BYELLOW} ] $1${RESET}"
}

# Pretty print for input (function).
input_print () {
    echo -ne "${BOLD}${BYELLOW}[ ${BGREEN}•${BYELLOW} ] $1${RESET}"
}

# Alert user of bad input (function).
error_print () {
    echo -e "${BOLD}${BRED}[ ${BBLUE}•${BRED} ] $1${RESET}"
}


# User enters a username (function).
username_selector () {
    echo
    input_print "Please enter the name of your user: "
    read -r username
    if [[ -z "$username" ]]; then
        error_print "You need to enter a username in order to continue!"
        return 1
    fi

    return 0
}



# Welcome screen.
echo -ne "${BOLD}${BGREEN}
=========================================================

███╗   ██╗██╗██╗  ██╗ ██████╗ ███████╗
████╗  ██║██║╚██╗██╔╝██╔═══██╗██╔════╝
██╔██╗ ██║██║ ╚███╔╝ ██║   ██║███████╗
██║╚██╗██║██║ ██╔██╗ ██║   ██║╚════██║
██║ ╚████║██║██╔╝ ██╗╚██████╔╝███████║
╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝                                
                                                      
=========================================================
${RESET}"
info_print "Welcome to the installation of NixOS! :)"
echo

# Choosing the target for the installation.
info_print "Available disks for the installation:"
echo
lsblk
echo
PS3="Please select the number of the corresponding disk (e.g. 1): "
echo
select ENTRY in $(lsblk -dpnoNAME|grep -P "/dev/sd|nvme|vd");
do
    DISK="$ENTRY"
    echo
    info_print "NixOS will be installed on the following disk: $DISK"
    break
done

# Warn user about deletion of old partition scheme.
echo
input_print "WARNING! This WILL wipe the current partition table on $DISK. Do you agree [y/N]?: "
read -r disk_response
if ! [[ "${disk_response,,}" =~ ^(yes|y)$ ]]; then
    error_print "Quitting."
    exit
fi
echo
info_print "Wiping $DISK."
sudo wipefs -af "$DISK" &>/dev/null
sudo sgdisk -Zo "$DISK" &>/dev/null

# User choses the hostname.
until username_selector; do : ; done

# Creating a new partition scheme.
echo
info_print "Creating the partitions on $DISK."
sudo parted -s "$DISK" mklabel gpt
sudo parted -s "$DISK" mkpart NIXBOOT fat32 1MiB 513MiB
sudo parted -s "$DISK" set 1 esp on
# Sjekk RAM og avgjør om swap skal opprettes
RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
RAM_GB=$((RAM_KB / 1024 / 1024))
USE_SWAP=false
if [ "$RAM_KB" -le $((16 * 1024 * 1024)) ]; then
    USE_SWAP=true
fi

# Dynamisk partisjonering basert på diskstørrelse
DISK_SIZE_B=$(lsblk -b -dn -o SIZE "$DISK")
DISK_SIZE_GB=$((DISK_SIZE_B / 1024 / 1024 / 1024))
BOOT_END=513MiB
SWAP_SIZE_GB=10
SWAP_SIZE_MIB=$((SWAP_SIZE_GB * 1024))
if [ "$USE_SWAP" = true ]; then
    info_print "Systemet har 16GB RAM eller mindre. Oppretter 10GiB swap-partisjon."
    # Beregn ledig plass etter boot og swap
    REMAINING_GB=$((DISK_SIZE_GB - SWAP_SIZE_GB - 1/2)) # 1/2 for å være sikker på avrunding
    ROOT_SIZE_GB=$((REMAINING_GB / 2))
    HOME_SIZE_GB=$((REMAINING_GB - ROOT_SIZE_GB))
    ROOT_END="$((513 + ROOT_SIZE_GB * 1024))MiB"
    HOME_END="$((513 + (ROOT_SIZE_GB + HOME_SIZE_GB) * 1024))MiB"
    SWAP_START="$((DISK_SIZE_GB - SWAP_SIZE_GB))GiB"
    sudo parted -s "$DISK" mkpart NIXROOT 513MiB $ROOT_END
    sudo parted -s "$DISK" mkpart NIXHOME $ROOT_END $SWAP_START
    sudo parted -s "$DISK" mkpart NIXSWAP $SWAP_START 100%
else
    REMAINING_GB=$((DISK_SIZE_GB - 1/2))
    ROOT_SIZE_GB=$((REMAINING_GB / 2))
    ROOT_END="$((513 + ROOT_SIZE_GB * 1024))MiB"
    sudo parted -s "$DISK" mkpart NIXROOT 513MiB $ROOT_END
    sudo parted -s "$DISK" mkpart NIXHOME $ROOT_END 100%
fi

NIXBOOT="/dev/disk/by-partlabel/NIXBOOT"
NIXROOT="/dev/disk/by-partlabel/NIXROOT"
NIXHOME="/dev/disk/by-partlabel/NIXHOME"
if [ "$USE_SWAP" = true ]; then
    NIXSWAP="/dev/disk/by-partlabel/NIXSWAP"
fi

# Spør om kryptering av root og home
read -rp "Ønsker du å kryptere root og home med LUKS? (y/n): " ENCRYPT
if [[ "$ENCRYPT" =~ ^[YyJj]$ ]]; then
    while true; do
        read -rsp "Skriv inn passphrase for disk-kryptering: " LUKS_PASSPHRASE
        echo
        read -rsp "Gjenta passphrase: " LUKS_PASSPHRASE2
        echo
        if [ "$LUKS_PASSPHRASE" = "$LUKS_PASSPHRASE2" ]; then
            break
        else
            echo "Passordene var ikke like. Prøv igjen."
        fi
    done
    info_print "Krypterer root-partisjon med LUKS..."
    echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup luksFormat "$NIXROOT" \
  --type luks2 \
  --cipher aes-xts-plain64 \
  --key-size 512 \
  --pbkdf argon2id \
  --pbkdf-memory 1048576 \
  --pbkdf-parallel 4 \
  --pbkdf-force-iterations 10 \
  -q --batch-mode --key-file -
    echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup open "$NIXROOT" cryptroot --key-file -
    NIXROOT="/dev/mapper/cryptroot"
    info_print "Krypterer home-partisjon med LUKS..."
    echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup luksFormat "$NIXHOME" \
  --type luks2 \
  --cipher aes-xts-plain64 \
  --key-size 512 \
  --pbkdf argon2id \
  --pbkdf-memory 1048576 \
  --pbkdf-parallel 4 \
  --pbkdf-force-iterations 10 \
  -q --batch-mode --key-file -
    echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup open "$NIXHOME" crypthome --key-file -
    NIXHOME="/dev/mapper/crypthome"
    if [ "$USE_SWAP" = true ]; then
        info_print "Krypterer swap-partisjon med LUKS..."
        echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup luksFormat "$NIXSWAP" \
  --type luks2 \
  --cipher aes-xts-plain64 \
  --key-size 512 \
  --pbkdf argon2id \
  --pbkdf-memory 1048576 \
  --pbkdf-parallel 4 \
  --pbkdf-force-iterations 10 \
  -q --batch-mode --key-file -
        echo -n "$LUKS_PASSPHRASE" | sudo cryptsetup open "$NIXSWAP" cryptswap --key-file -
        NIXSWAP="/dev/mapper/cryptswap"
    fi
fi

# Formater partisjoner
info_print "Formaterer EFI-partisjon som FAT32."
sudo mkfs.fat -F 32 "$NIXBOOT"
info_print "Formaterer root-partisjon som btrfs."
sudo mkfs.btrfs -f "$NIXROOT"
if [ "$USE_SWAP" = true ]; then
    info_print "Formaterer swap-partisjon."
    sudo mkswap "$NIXSWAP"
fi

echo
info_print "Monterer og oppretter BTRFS subvolumer."
sudo mkdir -p /mnt
sudo mount "$NIXROOT" /mnt
subvols=(root home nix log)
for subvol in "${subvols[@]}"; do
    sudo btrfs su cr /mnt/@$subvol
fi
sudo umount -l /mnt

info_print "Monterer subvolumer med optimale opsjoner."
# Monter subvolumer med optimale opsjoner (kun btrfs, ingen dobbel mounting)
sudo mount -o subvol=@root,compress=zstd,space_cache=v2,noatime,discard=async,ssd "$NIXROOT" /mnt
sudo mkdir -p /mnt/{home,nix,var/log,boot}
sudo mount -o subvol=@home,compress=zstd,space_cache=v2,noatime,discard=async,ssd "$NIXROOT" /mnt/home
sudo mount -o subvol=@nix,compress=zstd,space_cache=v2,noatime,discard=async,ssd "$NIXROOT" /mnt/nix
sudo mount -o subvol=@log,compress=zstd,space_cache=v2,noatime,discard=async,ssd "$NIXROOT" /mnt/var/log
# NB: Ikke bruk autodefrag på SSD, kun på roterende disk hvis nødvendig
sudo mount "$NIXBOOT" /mnt/boot
if [ "$USE_SWAP" = true ]; then
    sudo swapon "$NIXSWAP"
fi

mount_filesystems () {
  echo
  info_print "Sørger for at partisjonene er montert."
  sudo umount -l /mnt || true
  sudo mount "$NIXROOT" /mnt
  sudo mkdir -p /mnt/home
  sudo mount "$NIXHOME" /mnt/home
  sudo mkdir -p /mnt/boot
  sudo mount "$NIXBOOT" /mnt/boot
  if [ "$USE_SWAP" = true ]; then
    sudo swapon "$NIXSWAP"
  fi

  info_print "Genererer hardware-config (hardware-configuration.nix)"
  sudo nixos-generate-config --root /mnt
  return 0
}


echo
info_print "Installerer systemet med flakes."
sudo nixos-install --no-root-passwd --flake /mnt/etc/nixos#$(hostname) && clear